Add support for different CBOR tags to be used for CBOR-LD to identify required application context maps.
json-ld/cbor-ld-spec pull request #28
Opened 2024-07-01 13:19 UTC by wes-smith

- defines CBOR tag/varint system needed for retrieving data needed for decoding
- defines registry system for registering tables associated with a tag/varint
- adds new algorithms to support the above
- updates existing algorithms to support the above

***
<a href="https://pr-preview.s3.amazonaws.com/wes-smith/cbor-ld-spec/pull/28.html" title="Last updated on Jul 15, 2024, 1:36 PM UTC (c79af99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/json-ld/cbor-ld-spec/28/4edf4bc...wes-smith:c79af99.html" title="Last updated on Jul 15, 2024, 1:36 PM UTC (c79af99)">Diff</a>

2024-07-01 15:43 UTC, dlongley commented on index.html
> +To this end, we have registered the range of CBOR tags 1500-1800** to be used for CBOR-LD,
1500-1535 and 1792-1800 are reserved for other purposes and any future revisions that may/may not impact compression table lookups.

```suggestion
To this end, we have registered the range of CBOR tags 1536-1791** (0x0600-0x06FF) to be used for CBOR-LD,
```

2024-07-01 15:43 UTC, dlongley commented on index.html
> +as the beginning of a varint. If the CBOR tag is `0x0680`, the first item in the CBOR payload
We should probably also mention `0x0600-0x067F` for completion.

2024-07-01 15:43 UTC, dlongley commented on index.html
> +MUST be a major type 2 byte string containing the rest of the varint. See Algorithm <a
Just a note: I have to look at an implementation (or closely at the algorithms below) to determine if this description ("major type 2 byte string containing...") is accurate. If that includes expressing that type in the byte string, that isn't what we want here (I don't think). We want to be able to run `number = varint([second byte of CBOR tag, ...])`, so if `varint()` shouldn't have to do any CBOR parsing.

2024-07-01 15:43 UTC, dlongley commented on index.html
> +required for decompression. A  <b>CBOR-LD Varint Registry Entry</b> contains the following:
```suggestion
required for decompression. A <b>CBOR-LD Varint Registry Entry</b> contains the following:
```

2024-07-01 15:43 UTC, dlongley commented on index.html
> +varint Value: an integer no smaller than 1500.
```suggestion
varint Value: an integer no smaller than 1536.
```

2024-07-01 15:43 UTC, dlongley commented on index.html
> +as these context URLs are encoded as integers, the consumer of the CBOR-LD
Context URLs are not always encoded as integers, they only will be if they are present in the table. Additional context URLs can be included, but they will be expressed as strings. Similarly, embedded contexts (objects/arrays) can be included.

2024-07-02 03:06 UTC, TallTed requested changes

2024-07-02 03:06 UTC, TallTed commented on index.html
>  an arbitrary CBOR-LD consumer to decompress any CBOR-LD payload meeting this specification.
```suggestion
the URLs of the contexts needed to create the term codec map can be encoded as integers
by CBOR-LD. If a CBOR-LD payload contains context URLs compressed in such a way, a
consumer of the CBOR-LD will need to reconstruct the term codec map, for which they
will need to know what `Compression Table` (map from JSON-LD terms to integers) was
used to compress the context URLs during creation of the CBOR. The following sections
define the exact mechanism by which this can be accomplished, allowing an arbitrary
CBOR-LD consumer to decompress any CBOR-LD payload that complies with this
specification.
```

2024-07-02 03:06 UTC, TallTed commented on index.html
> +as the beginning of a varint. If the CBOR tag is in the range (0x0600-0x067F), the last byte of
```suggestion
as the beginning of a varint. If the CBOR tag is in the range `0x0600`–`0x067F`, the last byte of
```

2024-07-12 15:12 UTC, dlongley commented on index.html
> +      </ol>
@wes-smith as you know we'll need to update this with the new table layout (string, url scheme, typed-literal, etc.). But we also need to include that a registry entry indicates a "processing model" and we need to indicate that there is a "default" processing model that every entry uses unless otherwise specified and that refers to the algorithms in this spec (either present or not yet added).  The processing model indicates how context-based, auto-generated term IDs are generated, what the core / generic type-encoders are (e.g., for date compression) and so on.

2024-07-15 13:27 UTC, msporny commented on index.html
> +consumer of the CBOR-LD must know what compression tables (maps from JSON-LD terms to integers)
```suggestion
consumer of the CBOR-LD needs to know what compression tables (maps from JSON-LD terms to integers)
```

2024-07-15 13:27 UTC, msporny commented on index.html
> +was used to compress the context URLs during creation to be able to reconstruct the term codec
```suggestion
were used to compress the context URLs during creation to be able to reconstruct the term codec
```

2024-07-15 13:29 UTC, msporny commented on index.html
> +    </p>
```suggestion
    <p class="issue">
This exact range of tag values has not yet been officially registered with
<a href="https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml">the IANA CBOR
Tag Registry</a>. The exact range is subject to change.
    </p>
```

2024-07-15 13:32 UTC, msporny commented on index.html
> +`typeTables`: an array containing what `Type Tables` must be used for this
```suggestion
`typeTables`: an array containing what `Type Tables` are to be used for this
```

2024-07-15 13:36 UTC, merged