Update algorithms to use new processing model.
json-ld/cbor-ld-spec pull request #30
Opened 2024-08-27 19:51 UTC by wes-smith

2024-08-28 19:46 UTC, TallTed requested changes

2024-08-28 19:46 UTC, TallTed commented on index.html
> +document to `typeTable`. If "callerProvidedTable" appears in contextTables, populate `typeTables`
```suggestion
document to `typeTable`. If "callerProvidedTable" appears in `contextTables`, populate `typeTables`
```

2024-08-28 19:46 UTC, TallTed commented on index.html
> +This algorithm takes a CBOR-LD payload `cborldBytes` as input and returns
```suggestion
This algorithm takes a CBOR-LD payload `cborldBytes` as input, and returns
```

2024-08-28 19:46 UTC, TallTed commented on index.html
> +Otherwise if the CBOR tag on `cborldBytes` is in the range `0x0600-0x067F`, set `registryEntryId` to
```suggestion
If the CBOR tag on `cborldBytes` is not in the range `0x0600`–`0x06FF`, throw an
`ERR_NON_CBOR_LD_TAG` error.
          </li>
          <li>
Otherwise if the CBOR tag on `cborldBytes` is in the range `0x0600`–`0x067F`, set `registryEntryId` to
```

2024-08-28 19:46 UTC, TallTed commented on index.html
> +ERR_INVALID_VARINT_VALUE error.
```suggestion
`ERR_INVALID_VARINT_VALUE` error.
```

2024-08-28 19:46 UTC, TallTed commented on index.html
> +This algorithm takes as input CBOR-LD payload `cborldBytes` and a map `typeTable` and returns a JSON-LD document.
```suggestion
This algorithm takes a CBOR-LD payload `cborldBytes` and a map `typeTable` as inputs, and returns a JSON-LD document.
```

2025-01-06 15:40 UTC, dlongley approved these changes
I think this is a significant improvement over what we have in the spec today, so we should merge this and iterate from there.

2025-01-06 15:46 UTC, dlongley commented on index.html
> +If the CBOR tag on `cborldBytes` is not in the range `0x0600-0x06FF`, throw an
```suggestion
If the CBOR tag on `cborldBytes` is not in the range `0x0600`-`0x06FF`, throw an
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +Otherwise if the CBOR tag on `cborldBytes` is in the range `0x0600-0x067F`, set `registryEntryId` to
```suggestion
Otherwise if the CBOR tag on `cborldBytes` is in the range `0x0600`-`0x067F`, set `registryEntryId` to
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +ERR_INVALID_VARINT_VALUE error.
```suggestion
`ERR_INVALID_VARINT_VALUE` error.
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +If the CBOR tagged item is not an array containing exactly two elements, throw an ERR_INVALID_VARINT_STRUCTURE
```suggestion
If the CBOR tagged item is not an array containing exactly two elements, throw an `ERR_INVALID_VARINT_STRUCTURE`
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +not an array, throw an error ERR_INVALID_ENCODED_CONTEXT.
```suggestion
not an array, throw an `ERR_INVALID_ENCODED_CONTEXT` error.
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +ERR_INVALID_ENCODED_CONTEXT.
```suggestion
If `contextTermId` also had an entry in `input` during the previous check, throw an
`ERR_INVALID_ENCODED_CONTEXT` error.
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +This algorithm takes maps `state`, `activeContext`, `input` as inputs and
```suggestion
This algorithm takes maps `state`, `activeContext`, `input` as inputs, and
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +This algorithm takes maps `state`, `activeContext` and `input` as input and
```suggestion
This algorithm takes maps `state`, `activeContext`, and `input` as inputs, and
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +This algorithm takes maps `state`, `activeContext` and a string `term` as input and
```suggestion
This algorithm takes maps `state`, `activeContext`, and a string `term` as inputs and
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +This algorithm takes maps `state`, `activeContext` and a set `objectTypes` as input and
```suggestion
This algorithm takes maps `state`, `activeContext` ,and a set `objectTypes` as inputs, and
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +This algorithm takes an encoded CBOR-LD payload `cborldBytes` as input and returns
```suggestion
This algorithm takes an encoded CBOR-LD payload `cborldBytes` as input, and returns
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +document `jsonldDocument` as input and returns a hexadecimal string `cborldBytes`.
```suggestion
document `jsonldDocument` as inputs, and returns a hexadecimal string `cborldBytes`.
```

2025-01-06 15:46 UTC, dlongley commented on index.html
> +as input and returns a map containing maps `state` and `output`.
```suggestion
as inputs, and returns a map containing maps `state` and `output`.
```

2025-01-06 15:49 UTC, dlongley commented
I believe I've applied all of @TallTed's suggestions that still remained after the most recent edits.

2025-01-06 17:26 UTC, wes-smith commented
@TallTed How do you want to proceed here? This PR is pretty huge - do you intend to do a full rereview, and if so, how long do you think it will take?

2025-01-06 22:12 UTC, TallTed requested changes
Editorial. Almost only commas and code fences, for clarity.

2025-01-06 22:12 UTC, TallTed commented on index.html
> +If `intValue` is not in `subTable`. throw an error ERR_UNKNOWN_COMPRESSED_VALUE.
```suggestion
If `intValue` is not in `subTable`, throw an error ERR_UNKNOWN_COMPRESSED_VALUE.
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +0xD906.
```suggestion
`0xD906`.
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +Set `varintTagValue` to `varintArray[0]` appended to the end of the bytes 0xD906.
```suggestion
Set `varintTagValue` to `varintArray[0]` appended to the end of the bytes `0xD906`.
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +to the end of the bytes 0x82.
```suggestion
to the end of the bytes `0x82`.
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +Otherwise if `valueToDecode` is an integer and `state`.`typesEncodedAsBytes` does not
```suggestion
Otherwise, if `valueToDecode` is an integer and `state`.`typesEncodedAsBytes` does not
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +Otherwise if `valueToDecode` is a byte array and `tableType` is not "none", set
```suggestion
Otherwise, if `valueToDecode` is a byte array and `tableType` is not "none", set
```

2025-01-06 22:12 UTC, TallTed commented on index.html
> +Otherwise if the CBOR tag on `cborldBytes` is in the range `0x0600`-`0x067F`, set `registryEntryId` to
```suggestion
Otherwise, if the CBOR tag on `cborldBytes` is in the range `0x0600`-`0x067F`, set `registryEntryId` to
```

2025-01-13 16:36 UTC, wes-smith commented
@TallTed Thanks, suggestions applied.

2025-01-13 19:57 UTC, gkellogg approved these changes
This document is a major improvement over the previous. Note my comments about leveraging the JSON-LD Internal Representation more, rather than sticking to JSON directly. I didn't make this a change request, as I think this can be merged as is, but a future PR should normalize the nomenclature.

2025-01-13 19:57 UTC, gkellogg commented on index.html
> +document `jsonldDocument` as inputs, and returns a hexadecimal string `cborldBytes`.
To be consistent with how JSON-LD is defined, and the use within YAML-LD, we should talk about transformation to and from the JSON-LD [Internal Representation](https://www.w3.org/TR/json-ld11-api/#dfn-internal-representation). This might, instead, say "and a JSON-LD Document in the Internal Representation".

Generally, the "JSON-LD document" could be serialized in different formats, but the algorithms should only need to be aware of the INFRA-based Internal Representation.

2025-01-13 19:57 UTC, gkellogg commented on index.html
> +This algorithm takes a CBOR-LD payload `cborldBytes`, and returns a JSON-LD document `jsonldDocument`.
See above comment about leveraging the Internal Representation.

2025-01-13 19:57 UTC, gkellogg commented on index.html
> +converting inputs between data forms. When used in conjunction with a "strategy",
Again, a "converter" would convert inputs to and from the Internal Representation to CBOR-LD; we shouldn't tie ourselves to the JSON serialization.

2025-01-14 21:47 UTC, TallTed approved these changes
lgtm!

2025-01-15 18:28 UTC, dlongley commented
Multiple approvals, suggestions accepted, merging. Thanks!

2025-01-15 18:28 UTC, merged